# Generated by Django 3.1.4 on 2022-07-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
