# Generated by Django 3.1.4 on 2022-07-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220712_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='gate_unique_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
