# Generated by Django 3.1.4 on 2022-07-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220712_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='car_model_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='car_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
