# Generated by Django 3.1.4 on 2022-07-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220712_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='car_model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='car_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
