# Generated by Django 3.1.4 on 2022-07-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220712_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_gate', to='core.gate'),
        ),
    ]
