# Generated by Django 3.1.4 on 2022-07-12 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_person_gate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_gate', to='core.gate'),
        ),
    ]
